name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build both server and client
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean war --info
      - uses: actions/upload-artifact@master
        with:
          name: buildres
          path: build
  unittest-server:
    runs-on: ubuntu-latest
    needs: build
    name: Unit test server
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/download-artifact@master
        with:
          name: buildres
          path: build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit test server
        run: ./gradlew test --info
  integration-test:
    runs-on: ubuntu-latest
    needs: unittest-server
    name: Run integration tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Download Tomcat
        run: wget -c https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.11/bin/apache-tomcat-10.1.11.tar.gz -O - | tar -xz
      - name: Clean ROOT dir
        run: rm -rf apache-tomcat-10.1.11/webapps/ROOT
      - uses: actions/download-artifact@master
        with:
          name: buildres
          path: build
      - name: Add .war file
        run: cp build/libs/template-plain.war apache-tomcat-10.1.11/webapps
      - name: Rename .war
        run: mv apache-tomcat-10.1.11/webapps/template-plain.war apache-tomcat-10.1.11/webapps/ROOT.war
      - name: Start server
        run: ./apache-tomcat-10.1.11/bin/startup.sh
      - name: Run integration tests
        run: ./gradlew webTest --info -Dselenide.headless=true
      - name: Stop server
        run: ./apache-tomcat-10.1.11/bin/shutdown.sh