name: Java CI with Gradle

on: [ push, pull_request ]

stages:
  - stage: Test
    jobs:
      build-server:
          runs-on: ubuntu-latest
          displayName: Build server
          steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'adopt'
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew clean bootWar --info
      unittest-server:
          runs-on: ubuntu-latest
          needs: build-server
          displayName: Unit test server
          steps:
            - uses: actions/checkout@v3
            - name: Unit test server
              run: ./gradlew test ---info
      run-server:
        runs-on: ubuntu-latest
        needs: unittest-server
        displayName: Run server
        steps:
          - uses: actions/checkout@v3
          - name: Download Tomcat
            run: wget -c https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.11/bin/apache-tomcat-10.1.11.tar.gz -O - | tar -xz
          - name: Clean ROOT dir
            run: rm -rf apache-tomcat-10.1.11/webapps/ROOT
          - name: Add .war file
            run: cp build/libs/template.war apache-tomcat-10.1.11/webapps
          - name: Rename .war
            run: mv apache-tomcat-10.1.11/webapps/template.war apache-tomcat-10.1.11/webapps/ROOT.war
          - name: Start server
            run: ./apache-tomcat-10.1.11/bin/startup.sh
      build-client:
        runs-on: ubuntu-latest
        displayName: Build client
        steps:
          - uses: actions/checkout@v3
          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: 18
          - name: Install node dependencies
            run: npm install
          - name: Build client
            run: npm run build